package com.example.javaegitimleri.degiskenler;

public class Odev1 {
    public static void main(String[] args) {
        String ilce = "Kayapınar";
        System.out.println(ilce);
        String kita = "Afrika";
        System.out.println(kita);
        int faks = 555-123-4567;
        System.out.println(faks);
        int postaKodu = 34000;
        System.out.println(postaKodu);
        String instaAdresi = "instagram.com/kullaniciadim";
        System.out.println(instaAdresi);
        String calistiginBolum = "Yazılım";
        System.out.println(calistiginBolum);
        int urunMiktari = 100;
        System.out.println(urunMiktari);
        String musteriSoyadi = "Demir";
        System.out.println(musteriSoyadi);
        double odemeMiktari = 250.50;
        System.out.println(odemeMiktari);
        String dogumTarihi = "21/11/1998";
        System.out.println(dogumTarihi);
        double borc = 500.00;
        System.out.println(borc);
        String medeniHal = "Bekar";
        System.out.println(medeniHal);
        String videoYorumu = "Harika bir video!";
        System.out.println(videoYorumu);
        String odemeSaati = "15:30";
        System.out.println(odemeSaati);
        int eftMiktari = 300;
        System.out.println(eftMiktari);
        int satilanMiktar = 50;
        System.out.println(satilanMiktar);
        String telefonModeli = "Samsung";
        System.out.println(telefonModeli);
        String dergiAdi = "Kafa";
        System.out.println(dergiAdi);
        String basimTarihi = "25/05/2023";
        System.out.println(basimTarihi);
        double zamMiktari = 10.00;
        System.out.println(zamMiktari);
        int daireSayisi = 21;
        System.out.println(daireSayisi);
        double enlem = 40.37;
        System.out.println(enlem);
        double boylam = 41.20;
        System.out.println(boylam);
        String yemekAdi = "İçli Köfte";
        System.out.println(yemekAdi);
        double urunFiyati = 125.99;
        System.out.println(urunFiyati);
        String sirket = "Demir Ltd. Şti.";
        System.out.println(sirket);
        String videoAdi = "Java Eğitim Videoları";
        System.out.println(videoAdi);
        String muzikSuresi = "4 dakika 30 saniye";
        System.out.println(muzikSuresi);
        double mekanPuani = 4.5;
        System.out.println(mekanPuani);
        String dosyaAdi = "belge.doc";
        System.out.println(dosyaAdi);
        String resimFormati = "JPEG";
        System.out.println(resimFormati);
        String renk = "Sarı";
        System.out.println(renk);
        String renkKodu = "#ffff00";
        System.out.println(renkKodu);
        String bilgisayarModeli = "Lenovo z5070";
        System.out.println(bilgisayarModeli);
        double ekranBoyutu = 15.6;
        System.out.println(ekranBoyutu);
        String kullanimSuresi = "2 yıl";
        System.out.println(kullanimSuresi);
        String basinc = "120/80 mmHg";
        System.out.println(basinc);
        String etkinlikGunu = "Cumartesi";
        System.out.println(etkinlikGunu);
        String odemeGunu = "20 Temmuz";
        System.out.println(odemeGunu);
        String yolculukCikisTarihi = "10/11/2023";
        System.out.println(yolculukCikisTarihi);
        String mahalleAdi = "Diclekent Mahallesi";
        System.out.println(mahalleAdi);
        String otobusHatti = "E1";
        System.out.println(otobusHatti);
        int kullanilanDakika = 500;
        System.out.println(kullanilanDakika);
        String kargoTakipNo = "ykbn211198";
        System.out.println(kargoTakipNo);
        String kuponSuresi = "31 Aralık 2023";
        System.out.println(kuponSuresi);
        int kuponKodu = 89911998;
        System.out.println(kuponKodu);
        String faturaTarihi = "05/10/2023";
        System.out.println(faturaTarihi);
    }
}
